### ISSUE TITLE
Wrong versionCode in latest release

### ISSUE THREAD

**Issue by IzzySoft** [varunon9/Remote-Control-PC#11]
Please remember to update `versionCode` and `versionNumber` when making a new release. The latest two APKs both identify themselves as:

    package: name='com.example.remotecontrolpc' versionCode='1' versionName='1.0' platformBuildVersionName='6.0-2704002'

That way Android doesn't recognize the new version as being new, and won't accept it as "update". Just to let you know :wink:

**Comment by varunon9** [comment]
Thanks for pointing that out. i'll make sure 😃

**Comment by IzzySoft** [comment]
Hm. The one you just uploaded about an hour after closing this issue (according to its timestamp) says:

    package: name='me.varunon9.remotecontrolpc' versionCode='1' versionName='1.0' platformBuildVersionName='6.0-2704002'

Sure you've made sure? :wink:

**Comment by varunon9** [comment]
I guess new push is okay :p. Thanks again :D :D

**Comment by IzzySoft** [comment]
Do I pick it from the wrong location then? `https://github.com/varunon9/Remote-Control-PC/tree/master/RemoteControlPC-Studio/app/build/outputs/apk` wasn't changed. Found another one in `https://github.com/varunon9/Remote-Control-PC/blob/master/RemoteControlPC-Studio/app/`, also still `versionCode='1'`. A third location I couldn't detect.

Maybe you could attach the "installation files" (APK, JAR) to their corresponding `releases/` (see: [Creating releases](https://help.github.com/articles/creating-releases/) in the Github Help)?

**Comment by varunon9** [comment]
Thanks for link. I've updated releases. Is everything fine now?

**Comment by IzzySoft** [comment]
Almost:

* tag:v3.0 ≠ versionName:1.3.0 (expected tag: v1.3.0)
* `app-debug.apk`: that's most likely a debug compile. If that's intended, it's no show-stopper – but an `app-release.apk` is preferable (just let me know, because a debug APK I mark as such in the app's Metadata).
* did you change the package name? `com.example.remotecontrolpc` → `me.varunon9.remotecontrolpc`? No problem with that (makes sense), I just need to know.

**Comment by varunon9** [comment]
* changed tag
* uploaded app-release.apk
* yes I did to to upload on playstore. 
Now I guess it is done, isn't it?

**Comment by IzzySoft** [comment]
Yes! :+1: Perfect, thanks!

**Comment by varunon9** [comment]
Thank you for guiding me :D

**Comment by IzzySoft** [comment]
Glad to have been of assistance – and thanks for following my guidance! Find your app [here](https://apt.izzysoft.de/fdroid/index/apk/me.varunon9.remotecontrolpc) now. Whenever you do a new release as you did it know (tags matching versionName etc.), it will show up in my repo usually within 24h. So folks can include my repo with the F-Droid client and will be informed about new versions automatically.

If you're looking for other improvements: A `Changelog.md` in the repo's main directory might be a good idea, with some short bullet points for what's new/changed per version. That could be linked with the app's Metadata in my repo, and then would show up in the F-Droid client as well – so users can check with it before hitting the "update" button. Further, if you wish, ways for Donations (Bitcoin, Paypal, FlattR, whatever) can be included with the repo entry as well.

If you decide and implement any of those, simply update this issue to let me know :wink:

**Comment by varunon9** [comment]
Sure. I'll let you know. Thank you :)
