### ISSUE TITLE
Android App Works With Galaxy Nexus API17 Android 4.2 Virtual Device,, Crashed When Running On Android 5.x Virtual Device

### ISSUE THREAD

**Issue by samsmith2001** [varunon9/Remote-Control-PC#12]
The Android App Works with Galaxy Nexus API17 Android 4.2 Virtual Device,, But it Crashed When Running On Nexus 5X API21 Android 5.0 and above Virtual Devices.  However it started working again on Android 6.0  and above Virtual Device

Image of Virtual Device
![rc](https://user-images.githubusercontent.com/30851623/29102964-d18e88e0-7c8a-11e7-9e66-4706da9bb239.jpg)
Android Monitor
[RC.txt](https://github.com/varunon9/Remote-Control-PC/files/1210176/RC.txt)

**Comment by varunon9** [comment]
Fixed it. Check it again and please update me.
