### ISSUE TITLE
Cannot find files in mobile transferred from PC

### ISSUE THREAD

**Issue by AmmarCh** [varunon9/Remote-Control-PC#20]
Hi sir,
Im found your app very useful but i am unable to find files transferred  from my PC to mobile phone!

What is the path where these files are transferred?

Thanks in advance

**Comment by varunon9** [comment]
in a folder named RemoteControlPC inside sdcard/phone storage

**Comment by AmmarCh** [comment]
The application is not creating any folder in my mobile... its just load file and nothing happen!

**Comment by varunon9** [comment]
do you see any error at console? is file transfer from mobile to PC is
working?

**Comment by AmmarCh** [comment]
No, error on console, and file transferring from mobile to pc is working sir!

**Comment by varunon9** [comment]
could you make sure that app has write permission to device?
You can manually assign permission to apps.
