### ISSUE TITLE
only LiveScreen is working

### ISSUE THREAD

**Issue by N1c3** [varunon9/Remote-Control-PC#26]
i could establish a connection but the only working part of the app is the LiveScreen feature...
the PC Aplication tells me i am Connected to the app and the LiveScreen feature proves that, but i can not control the mouse or the keyboard of my notebook...

**Comment by varunon9** [comment]
Are you able to sync files?
Any errors for mouse control?

**Comment by N1c3** [comment]
i think it was a problem with the provided precompieled progs. when i build it on my own its working fine... no i was not able to sync files, i didn't get an error (maybe i just dont know where to find errorlogs.
