### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Kareem-Hassan** [varunon9/Remote-Control-PC#3]
I have errors in Netbeans and Eclipse too ( i prefer switch to android studio ) need video describe how to import project and run it ..

**Comment by varunon9** [comment]
What errors are you getting?
To import project in Netbeans follow these steps-
1. Download as zip
2. Extract the folder
3. You can import zip folder in Netbeans so you'll have to create RemoteControlPC-Desktop.zip and RemoteControlPC-Libraries.zip from the extracted folder
4. First import  RemoteControlPC-Libraries.zip and then RemoteControlPC-Desktop.zip.
5. To import click on File -> import -> import from zip (choose source zip folder and destination) 
6. After importing RemoteControlPC-Libraries followed by RemoteControlPC-Desktop, clean and build.

If you still get problems, I'll upload video.

**Comment by varunon9** [comment]
You will have to import android part of this project into eclipse. Follow this link to import http://agile.csc.ncsu.edu/SEMaterials/tutorials/import_export/ . If you want to switch to Android-studio, you will have to manually create all classes in android studio project. 
If you still get any specific error while importing into eclipse, you can reopen the issue.

**Comment by varunon9** [comment]
Sorry. You can import eclipse project in android-studio. Earlier I didn't know this.
