### ISSUE TITLE
when i run the jar file it not work.

### ISSUE THREAD

**Issue by ghost** [varunon9/Remote-Control-PC#31]
i download jar file from https://github.com/varunon9/Remote-Control-PC/blob/master/RemoteControlPC-JavaFXML/store/RemoteControlPC.jar but it not works in win 10.

**Comment by varunon9** [comment]
Are you getting any error?

**Comment by ghost** [comment]
when I run this jar file it note works. so , I import this project with intellij IDEA.

Then , I run this project.

It works fine. But, live screen option was not work.

when I run live screen it comes like this .

In intellij IDEA when i run run 

![1](https://user-images.githubusercontent.com/45443554/79231761-30ef6680-7e84-11ea-866c-a57531c00556.PNG)

`screenshot: 185188
Transfer Progress: 2
Transfer Progress: 4
Transfer Progress: 6
Transfer Progress: 8
Transfer Progress: 11
Transfer Progress: 13
Transfer Progress: 15
Transfer Progress: 17
Transfer Progress: 19
Transfer Progress: 22
Transfer Progress: 24
Transfer Progress: 26
Transfer Progress: 28
Transfer Progress: 30
Transfer Progress: 33
Transfer Progress: 35
Transfer Progress: 37
Transfer Progress: 39
Transfer Progress: 42
Transfer Progress: 44
Transfer Progress: 46
Transfer Progress: 48
Transfer Progress: 50
Transfer Progress: 53
Transfer Progress: 55
Transfer Progress: 57
Transfer Progress: 59
Transfer Progress: 61
Transfer Progress: 64
Transfer Progress: 66
Transfer Progress: 68
Transfer Progress: 70
Transfer Progress: 72
Transfer Progress: 75
Transfer Progress: 77
Transfer Progress: 79
Transfer Progress: 81
Transfer Progress: 84
Transfer Progress: 86
Transfer Progress: 88
Transfer Progress: 90
Transfer Progress: 92
Transfer Progress: 95
Transfer Progress: 97
Transfer Progress: 99
Transfer Progress: 100`

![2](https://user-images.githubusercontent.com/45443554/79231785-39e03800-7e84-11ea-9aeb-1bc1137a3697.PNG)

In my android device it comes like a sky blue screen.

![Screenshot_20200414-185946_Video Player](https://user-images.githubusercontent.com/45443554/79231162-46b05c00-7e83-11ea-9f58-b5f25230c0f1.jpg)

How can I solve this ?

why this not done for me?

I run this project in intellij IDEA  with Windows 10 os .

**Comment by varunon9** [comment]
Are you able to transfer files from Desktop to Mobile? Check if File Download & File transfer are working smoothly. It's related to Live Screen

**Comment by ghost** [comment]
![20200415_072547](https://user-images.githubusercontent.com/45443554/79290757-8d856c80-7eea-11ea-9a54-eb78470727fa.jpg)

I am not able to transfer files from Desktop to Mobile. It comes not connected to pc. 

Why this not done ?

Give a solution for this.

**Comment by varunon9** [comment]
Are you able to see "Connected" on connect screen?
It's possible that you got disconnected.
Try killing apps and re-connect.
File transfer/download should work smoothly.

**Comment by ghost** [comment]
On connect screen it show connected.

But , it not work.

Check this project and solve this why live screen not works for me?
I run this with windows 10 os and my android device with android 10.

**Comment by ghost** [comment]
I download  the jar file from this project then I run.
![1](https://user-images.githubusercontent.com/45443554/79525590-dec76480-8080-11ea-86c7-81869947857a.PNG)

But , the live screen not done.
I run this android app with my old device with android 6.0 then also it not done.
