### ISSUE TITLE
server is not listening

### ISSUE THREAD

**Issue by muafakul** [varunon9/Remote-Control-PC#4]
how to fix this bro >???

**Comment by varunon9** [comment]
What errors are you getting?
Run the desktop app via terminal/cmd using `java -jar RemoteControlPC-Desktop.jar`. You will get error details/exceptions (if any). Also make sure that you are entering correct IP address.

**Comment by varunon9** [comment]
Assuming that you figured out solution, I am closing this issue.

**Comment by Snehal7** [comment]
getting an error Server Not Found how to resolve it,
