### ISSUE TITLE
what is the purpose of 2nd ip address ?

### ISSUE THREAD

**Issue by ghost** [varunon9/Remote-Control-PC#42]
I am a student.  I want to learn about virtual box host-only network connection.

![79231785-39e03800-7e84-11ea-9aeb-1bc1137a3697](https://user-images.githubusercontent.com/65843311/111925515-2b0bf780-8acf-11eb-96c1-ca12dbf31f22.png)

1 St IP - LAN connection. 

2 no IP -  virtual box host-only network connection. 

Usually I am using 1st IP if I connect with  WiFi or mobile hotshot.

what is the purpose of 2nd ip address ?

Can you explain in detail ?

**Comment by varunon9** [comment]
Your machine can get various IP addresses allocated based on config, I tried to list all the IP Addresses so that you can make connection using any of them.

**Comment by ghost** [comment]
How can I connect this app with 2nd IP ?
