### ISSUE TITLE
Error:Failed to resolve: __local_jars__:G:\Workspace\StudioProject\RemortPc\app\libs\RemoteControlPC-Libraries.jar <a href="openFile:G:/Workspace/StudioProject/RemortPc/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

### ISSUE THREAD

**Issue by gowsikraja** [varunon9/Remote-Control-PC#5]
![untitled](https://cloud.githubusercontent.com/assets/23701518/23938204/550aa5b4-0981-11e7-9e9d-b784ec097010.png)

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "com.example.remotecontrolpc"
        minSdkVersion 11
        targetSdkVersion 24
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}
dependencies {
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    androidTestCompile files('libs/RemoteControlPC-Libraries.jar')
    compile '__local_jars__:G:\\Workspace\\StudioProject\\RemortPc\\app\\libs\\RemoteControlPC-Libraries.jar:unspecified'
}`

**Comment by varunon9** [comment]
Did you add RemoteControlPC-Libraries.jar as external library? It has been mentioned in README.
You can also visit http://stackoverflow.com/questions/25660166/how-to-add-a-jar-in-external-libraries-in-android-studio

**Comment by varunon9** [comment]
https://www.youtube.com/watch?v=mMPT4M0p4T8
Check this video to import android part to Android Studio

**Comment by gowsikraja** [comment]
Hi there,
     Thank-lot for quick response. And i done to import the project to
android studio above u mentioned video  and i facing two more issue and
also i fixed it. That problem comes from resource drawable-ldpi and
drawable-hdpi folders. It's contains pdf.png file and music_svg.svg file
respectively those files are crashed or unsupported format. Just i delete
that files and run.Yes it's working.
thanks one more..

**Comment by varunon9** [comment]
Great :)  :+1:
