### ISSUE TITLE
Server Not listenning Error

### ISSUE THREAD

**Issue by rameshkrr** [varunon9/Remote-Control-PC#6]
While connecting using IP address server not listening error occurs. Pls help.. Thanks

**Comment by varunon9** [comment]
Any error on console (desktop app) or logcat (android)??
To see console error, run jar file from cmd/terminal. Do read README carefully. You can also check youtube videos.

**Comment by rameshkrr** [comment]
Thanks for your reply. Now it's working perfectly.
