### ISSUE TITLE
Works like a charm on Virtual device but immediately crashes on real device

### ISSUE THREAD

**Issue by amanuelkiflu** [varunon9/Remote-Control-PC#9]
the android studio works on virtual device but it keeps crashing on any real device but however the non studio app was working like a charm, the problem is it doesn't include the live screen.

**Comment by varunon9** [comment]
What do you mean by "Android studio works on virtual device"? You don't need studio to run the app. Did you test the app (apk and jar file)?
Please post exceptions/errors and platform (Android version and OS) you are using.

**Comment by amanuelkiflu** [comment]
i mean that i imported the android studio project and it builds fine but when i run on an actual device it crashes immediately.
i am using android studio 2.3.3 and my android version is 5.0.1 lollipop.
thanks in advance

**Comment by amanuelkiflu** [comment]
if u currently tested the Android studio project, would you please send me as soon as you can?
thanks in advance.

**Comment by varunon9** [comment]
So you are trying to rebuild the project?? You can try already built apk on your phone to test https://github.com/varunon9/Remote-Control-PC/blob/master/RemoteControlPC-Studio/app/build/outputs/apk/app-debug.apk All the code here are in sync with my machine. Right now I am not working on it. You can watch the repository for any update. If you post error for crash or relevant screenshots, may be I can help.

**Comment by amanuelkiflu** [comment]
I did that but even that apk is crashing and I didn't only install it my
device, I tried it in 3 different devices but still crashes. You can even
try it on your own. I need help.

**Comment by varunon9** [comment]
I have only one device Android 4.2.2 and app works fine on it. I'll test app on new device next month. App crashes on live screen?? File transfer and File download works? Please post here error messages from android studio.

**Comment by meghabedi990** [comment]
even i have the same problem. I m using 5.1 lollipop. Also the file download is also not working..it is showing not connected to pc. I don't know why.

**Comment by varunon9** [comment]
I'll fix it in about 2-3 weeks because right now I've no other android version to test. 
I think bug is in this file https://github.com/varunon9/Remote-Control-PC/blob/master/RemoteControlPC-Studio/app/src/main/java/com/example/remotecontrolpc/FileAPI.java You can test this class in 'Hello world' app to check if line no 11 and 12 are printing correct path or not. If fixed you can have pull request.

**Comment by varunon9** [comment]
I have updated Android as well as Desktop app. Please download latest code and check once again
